"""'unique_fields'

Revision ID: c22c9bed63f1
Revises: dd9c2bae3b11
Create Date: 2025-11-19 13:09:58.618974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22c9bed63f1'
down_revision: Union[str, Sequence[str], None] = 'dd9c2bae3b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Task', ['title'])
    op.create_unique_constraint(None, 'User', ['email'])
    op.create_unique_constraint(None, 'User', ['password'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'Task', type_='unique')
    # ### end Alembic commands ###
