"""username added

Revision ID: dc3d340f2ad4
Revises: c22c9bed63f1
Create Date: 2025-12-16 16:41:23.076213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3d340f2ad4'
down_revision: Union[str, Sequence[str], None] = 'c22c9bed63f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint(op.f('User_password_key'), 'User', type_='unique')
    op.create_unique_constraint(None, 'User', ['username'])
    op.drop_column('User', 'lastName')
    op.drop_column('User', 'firstName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('firstName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'User', type_='unique')
    op.create_unique_constraint(op.f('User_password_key'), 'User', ['password'], postgresql_nulls_not_distinct=False)
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
